[project]
name = "argbench"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.42.44",
    "google-generativeai>=0.8.6",
    "openai>=2.17.0",
]

[tool.uv]
package = false
